
# jsp hot-swapping
server.jsp-servlet.init-parameters.development=true

server.context-parameters.dbms=oracle
server.context-parameters.url=jdbc:xxxx:orcl
server.context-parameters.greet=Hello!
server.context-parameters.hsseo=seo heon seob